import { Montserrat } from "next/font/google";
import "./globals.scss";
import Header from "../components/elements/Header";
import Footer from "../components/elements/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {/* Site Header */}
        <Header />

        {children}

        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
